### ISSUE TITLE
Fix Styling and Cleanup

### ISSUE THREAD

**Issue by glaciyan** [glaciyan/Lagersystem-Frontend#115]
Mit dem letzten styling refactor wurde das styling der kompletten seite kaputt gemacht. Dies sollte gelöst werden, siehe `uno.config.ts` und entferne die farbwerte und den `styles` ordner. Es gibt auch komponente die wie nicht mehr benutzen.
- Button
- headless-ui dependency in package.json
- `ElementProvider`, `MockSearch`, `Modal`, `PopOver`, `SelectorCustom`, `TheSearchHelp`, `TheClampedText`

Und natürlich auch selber schauen was auch nicht mehr benutzt wird, bei Gelegenheit auch Kevin fragen.

**Comment by Neoyx** [comment]
ToDo's:
- [ ] Entferne Farbwerte und styles ordner
- [ ] Entferne Button. ==> Welchen Button? GButton oder BaseButton?
- [ ] Entferne headless-ui dependency
- [ ] Entferne Komponenten wie ElementProvider, MockSearch etc. (siehe oben)

**Comment by glaciyan** [comment]
@Neoyx `SearchBar`, `RarityStars`, `GSpinner` können noch entfernt werden. Falls die irgendwo benutzt werden, kannst du diese Stellen entfernen. 👍

**Comment by Neoyx** [comment]
Erledigt

> @Neoyx `SearchBar`, `RarityStars`, `GSpinner` können noch entfernt werden. Falls die irgendwo benutzt werden, kannst du diese Stellen entfernen. 👍
 ==> Erledigt

**Comment by glaciyan** [comment]
PR machen und ich merge es rein
